FROM python:3.11-slim AS builder

WORKDIR /app
COPY requirements-inference.txt .
RUN pip install --no-cache-dir --target=/deps -r requirements-inference.txt


FROM python:3.11-slim

WORKDIR /app


COPY --from=builder /deps /usr/local/lib/python3.11/site-packages

COPY app/ ./app/
COPY model/ ./model/

CMD ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
