FROM python:3.11

WORKDIR /app

COPY requirements-baseline.txt .

RUN pip install --no-cache-dir --default-timeout=120 torch==2.4.1 torchvision==0.19.1 --index-url https://download.pytorch.org/whl/cpu
RUN pip install --no-cache-dir --default-timeout=120 fastapi==0.115.0 uvicorn==0.30.6 onnxruntime==1.19.2 pillow==10.4.0 numpy==1.26.4 python-multipart==0.0.9

COPY app/ ./app/
COPY model/ ./model/

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]